set_property PACKAGE_PIN AG24 [get_ports {dut_bus[31]}]
set_property PACKAGE_PIN AG25 [get_ports {dut_bus[30]}]
set_property PACKAGE_PIN AD23 [get_ports {dut_bus[29]}]
set_property PACKAGE_PIN AE23 [get_ports {dut_bus[28]}]
set_property PACKAGE_PIN AF23 [get_ports {dut_bus[27]}]
set_property PACKAGE_PIN AF24 [get_ports {dut_bus[26]}]
set_property PACKAGE_PIN AA22 [get_ports {dut_bus[25]}]
set_property PACKAGE_PIN AA23 [get_ports {dut_bus[24]}]
set_property PACKAGE_PIN AC24 [get_ports {dut_bus[23]}]
set_property PACKAGE_PIN AD24 [get_ports {dut_bus[22]}]
set_property PACKAGE_PIN Y22 [get_ports {dut_bus[21]}]
set_property PACKAGE_PIN Y23 [get_ports {dut_bus[20]}]
set_property PACKAGE_PIN AA24 [get_ports {dut_bus[19]}]
set_property PACKAGE_PIN AB24 [get_ports {dut_bus[18]}]
set_property PACKAGE_PIN V23 [get_ports {dut_bus[17]}]
set_property PACKAGE_PIN W24 [get_ports {dut_bus[16]}]
set_property PACKAGE_PIN AJ24 [get_ports {dut_bus[15]}]
set_property PACKAGE_PIN AJ23 [get_ports {dut_bus[14]}]
set_property PACKAGE_PIN AH22 [get_ports {dut_bus[13]}]
set_property PACKAGE_PIN AG22 [get_ports {dut_bus[12]}]
set_property PACKAGE_PIN AH24 [get_ports {dut_bus[11]}]
set_property PACKAGE_PIN AH23 [get_ports {dut_bus[10]}]
set_property PACKAGE_PIN AK20 [get_ports {dut_bus[9]}]
set_property PACKAGE_PIN AJ20 [get_ports {dut_bus[8]}]
set_property PACKAGE_PIN AJ19 [get_ports {dut_bus[7]}]
set_property PACKAGE_PIN AH19 [get_ports {dut_bus[6]}]
set_property PACKAGE_PIN AK18 [get_ports {dut_bus[5]}]
set_property PACKAGE_PIN AK17 [get_ports {dut_bus[4]}]
set_property PACKAGE_PIN AH21 [get_ports {dut_bus[3]}]
set_property PACKAGE_PIN AG21 [get_ports {dut_bus[2]}]
set_property PACKAGE_PIN AG20 [get_ports {dut_bus[1]}]
set_property PACKAGE_PIN AF20 [get_ports {dut_bus[0]}]

set_property PACKAGE_PIN AJ21 [get_ports {test_started}]

########################################################
#set_property PACKAGE_PIN AG21 [get_ports {dut_bus[10]}]
#set_property PACKAGE_PIN AH21 [get_ports {dut_bus[9]}]
#set_property PACKAGE_PIN AK17 [get_ports {dut_bus[8]}]
#set_property PACKAGE_PIN AK18 [get_ports {dut_bus[7]}]
#set_property PACKAGE_PIN AJ19 [get_ports {dut_bus[6]}]
#set_property PACKAGE_PIN AA23 [get_ports {dut_bus[5]}]
#set_property PACKAGE_PIN AA22 [get_ports {dut_bus[4]}]
#set_property PACKAGE_PIN AD23 [get_ports {dut_bus[3]}]
#set_property PACKAGE_PIN AG24 [get_ports {dut_bus[2]}]
#set_property PACKAGE_PIN AF20 [get_ports {dut_bus[1]}]
#set_property PACKAGE_PIN AG20 [get_ports {dut_bus[0]}]
#######################################################

##########################################################################


set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[31]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[30]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[29]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[28]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[27]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[26]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[25]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[24]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[23]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[22]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[21]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[20]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[19]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[18]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[17]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[16]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[11]}]


set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {dut_bus[0]}]

set_property IOSTANDARD LVCMOS25 [get_ports {test_started}]